dist: trusty
language: cpp
cache: apt
addons:
  apt:
    packages:
      - lcov
      - libmyodbc
      - libqt4-dev
      - libqt4-sql-mysql
      - libqt4-sql-odbc
      - libqt4-sql-psql
      - libqt4-sql-sqlite
      - libqt5sql5-mysql
      - libqt5sql5-odbc
      - libqt5sql5-psql
      - libqt5sql5-sqlite
      - odbc-postgresql
      - odbcinst
      - qtbase5-dev
services:
  - mysql
  - postgresql
env:
  - QT_SELECT=qt4 CONFIG=shared
  - QT_SELECT=qt4 CONFIG=static
  - QT_SELECT=qt5 CONFIG=shared
  - QT_SELECT=qt5 CONFIG=static
install:
  - tests/travis/install-build-depends
before_script:
  - mysql -e 'create database qdjango_test' -u root
  - psql -c 'create database qdjango_test' -U postgres
script:
  - tests/travis/build-and-test
